In [1]:
## Ejercicio 1
Num = float(input ("ingrese un número entero o decimal: "))
if Num < 0:
    Num = Num * -1
print(f"El valor absoluto de su número es {Num}")

ingrese un número entero o decimal: 7.8
El valor absoluto de su número es 7.8


In [3]:
## Ejercicio 2
Num1 = int(input ("ingrese un número entero: "))
Num2 = int(input ("ingrese un número entero: "))
Dif = abs(Num1 - Num2)
Check = 0
for i in range (2,Dif):
    if (Dif % i) == 0:
        Check = 1
        break
if Check == 0:
    print(f"la diferencia es {Dif} y SI es un numero primo")
elif Check == 1:
    print(f"la diferencia es {Dif} y NO es un numero primo")

ingrese un número entero: 6
ingrese un número entero: 13
la diferencia es 7 y SI es un numero primo


In [4]:
## Ejercicio 3
Contador = 0
M3 = []
M4 = []
print("Primeros 15 números multiplos de 3")
for i in range (1,101):
    if Contador < 15:
        if (i % 3) == 0:
            print(i)
            M3.append(i)
            Contador = Contador + 1
    elif Contador == 15:
        print("Multiplos de 4")
        Contador = Contador + 1
    elif (i % 4) == 0:
        print(i)
        M4.append(i)
print(M3)
print(M4)

Primeros 15 números multiplos de 3
3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
Multiplos de 4
48
52
56
60
64
68
72
76
80
84
88
92
96
100
[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45]
[48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100]


In [5]:
## Ejercicio 4
import numpy as np
x1 = int(input("ingrese la cordenada en x del circulo 1: "))
y1 = int(input("ingrese la cordenada en y del circulo 1: "))
r1 = int(input("ingrese el radio del circulo 1: "))
x2 = int(input("ingrese la cordenada en x del circulo 2: "))
y2 = int(input("ingrese la cordenada en y del circulo 2: "))
r2 = int(input("ingrese el radio del circulo 2: "))
A = int(input("ingrese la cordenada en x del punto: "))
B = int(input("ingrese la cordenada en y del punto: "))
D1 = np.sqrt((x1-A)**2 + (y1-B)**2)
D2 = np.sqrt((x2-A)**2 + (y2-B)**2)
if D1 < r1 and D2 < r2:
    print("el punto esta dentro de los 2 circulos")
elif D1 < r1:
    print("el punto esta dentro del circulo 1")
elif D2 < r2:
    print("el punto esta dentro del circulo 2")
else:
    print("el punto no esta dentro de ninguno de los circulos")

ingrese la cordenada en x del circulo 1: 5
ingrese la cordenada en y del circulo 1: 5
ingrese el radio del circulo 1: 2
ingrese la cordenada en x del circulo 2: 18
ingrese la cordenada en y del circulo 2: 18
ingrese el radio del circulo 2: 2
ingrese la cordenada en x del punto: 19
ingrese la cordenada en y del punto: 19
el punto esta dentro del circulo 2


In [6]:
## Ejercicio 5
import re
May = 0
Til = 0
Num = 0
Spa = 0
Text = input("ingrese una cadena de texto: ")
A = Text.count("in")
for i in (Text):
    if re.match("(A|E|I|O|U|Á|É|Í|Ó|Ú)",i):
        May = May + 1
    if re.match("(Á|É|Í|Ó|Ú|á|é|í|ó|ú)",i):
        Til = Til + 1
    if re.match("(1|2|3|4|5|6|7|8|9|0)",i):
        Num = Num + 1
    if re.match("( )",i):
        Spa = Spa + 1
print(f"el numero de vocales mayusculas con o sin tildes es {May}")
print(f"el numero de tildes es {Til}")
print(f"el numero de numeros es {Num}")
print(f"el numero de espacios es {Spa}")
print(f"el numero de palabras claves (in) es {A}")

ingrese una cadena de texto: áérmsw  ininAWSE5362
el numero de vocales mayusculas con o sin tildes es 2
el numero de tildes es 2
el numero de numeros es 4
el numero de espacios es 2
el numero de palabras claves (in) es 2


In [7]:
## Ejercicio 6
Orden = []
Texto = input("ingrese una cadena de texto: ")
Lista = list(Texto)
Lista.sort()
for i in (Lista):
    if i != " ":
        Orden.append(i)
print(Orden)

ingrese una cadena de texto: mi mama me ama
['a', 'a', 'a', 'a', 'e', 'i', 'm', 'm', 'm', 'm', 'm']


In [10]:
## Ejercicio 7
Lista = [2,2,3,3,5,5,5,5]
salir = False
for pos,i in enumerate(Lista):
    if pos <= Lista[-1]:
        if i > Lista[pos+1]:
            print("la lista no esta ordenada, ordenela para continuar")
            salir = True
            break 
if salir is False:
    num = int(input("ingrese un numero para ingresar a la lista: "))
    for posi,k in enumerate(Lista):
        if num < k:
            Lista.insert(posi,num)
            break
        if k == Lista[-1]:
            Lista.append(num)
            break
    print(Lista)

la lista no esta ordenada, ordenela para continuar


In [11]:
## Ejercicio 8
A = [4,3,6,54,23,87,2,1,3,87,87]

Mayr = max(A)
B = A.count(Mayr)
print(f"El numero mayor es {Mayr}")
for j in range(0,B):
    A.remove(Mayr)
May = max(A)
print(f"El segundo numero mayor es {May}")

El numero mayor es 87
El segundo numero mayor es 54


In [13]:
## Ejercicio 9
print("calculo de términos de la sucesión U(n+1) = 3*Un + 1 si Un es impar y U(n+1) = U(n)/2 si Un es par.")
u0 = int(input("Dame el valor de u0: "))
term = int(input("Cuantos terminos desea: "))
Serie= [u0]
for t in range(term-1):
    if (Serie[t] % 2) != 0:
        Serie.append(int((Serie[t]*3)+1))
    else:
        Serie.append(int(Serie[t]/2))
print(Serie)

calculo de términos de la sucesión U(n+1) = 3*Un + 1 si Un es impar y U(n+1) = U(n)/2 si Un es par.
Dame el valor de u0: 1
Cuantos terminos desea: 7
[1, 4, 2, 1, 4, 2, 1]


In [6]:
## Ejercicio 10
import numpy as np
Mat = np.random.randint(1,100,(4,5))
print(f"{Mat}\n")
Tot1 = Mat[3, :]
Tot1 = Tot1[::-1]
Mat = np.delete(Mat, 3, axis=0)
Tot2 = Mat[:, 0]
Tot2 = Tot2[::-1]
Mat = np.delete(Mat, 0, axis=1)
Tot3 = Mat[0, :]
Mat = np.delete(Mat, 0, axis=0)
Tot4 = Mat[:, 3]
Mat = np.delete(Mat, 3, axis=1)
Tot5 = Mat[1, :]
Tot5 = Tot5[::-1]
Tot6 = Mat[0, :]
Tot = np.append(Tot1,Tot2) 
Tot = np.append(Tot,Tot3)
Tot = np.append(Tot,Tot4)
Tot = np.append(Tot,Tot5)
Tot = np.append(Tot,Tot6) 
print(Tot)

[[ 6  5 42 85 11]
 [88 13 29 52 86]
 [66 29 89 64 85]
 [82 57 11 62 35]]

[35 62 11 57 82 66 88  6  5 42 85 11 86 85 64 89 29 13 29 52]


In [7]:
#Ejercicio número 11
anchura = int(input("Anchura del rectángulo: "))
altura = int(input("Altura del rectángulo: "))

for i in range(altura):
    for j in range(anchura):
        print("* ", end="")
    print()

Anchura del rectángulo: 5
Altura del rectángulo: 4
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [8]:
#Ejercicio número 12
def fun1(x):
    for i in range (1,x+1):
        print('x'*i)
    for j in range(x-1,0,-1):
        print ('x'*j)
x = int(input('escriba el ancho del triangulo: '))   
fun1(x)


escriba el ancho del triangulo: 3
x
xx
xxx
xx
x


In [15]:
#Ejercicio número 13
def fun():
    contar = 0
    if a >= b:
        print(f'por favor, ingrese un año final mayor: ')
    elif a < b: 
        for i in range(a,b+1):
            c = i%4
            d = i%100
            e = i%400
            if c == 0 and d != 0:
                contar += 1
            elif c == 0 and d == 0 and e == 0:
                contar += 1
        print(f'del año {a} al año {b} hay {contar} añor bisciestos. ')  
a = int(input('escriba un año inicial: '))
b = int(input('escriba un año final: '))
                
fun()

escriba un año inicial: 2000
escriba un año final: 2010
del año 2000 al año 2010 hay 3 añor bisciestos. 


In [16]:
#Ejercicio número 14
import random as ran    
def fun():  
    '''Esta función define la suma de 2 numeros entre 1 y 100'''       
   
    aciertos = 5
    
    while aciertos > 0:       
                                    
        num1 = ran.randint(1,100) 
        num2 = ran.randint(1,100)
        suma = num1+num2
        
        print(f"La suma propuesta es {num1} + {num2} = ")
        a = float(input("Digita el valor de la suma =  "))
        if a == suma:
            print("¡RESPUESTA CORRECTA!, la suma es =  ",suma) 
            aciertos = aciertos -1 
            f = 5 - aciertos 
            print(f"Has tenido {f} sumas buenas ")
        else:
                  print("¡INCORRECTO!, vuelve a intentarlo ")
                  
    print("¡FELICIDADES, TERMINASTE!")       
         
fun()       

La suma propuesta es 8 + 46 = 
Digita el valor de la suma =  54
¡RESPUESTA CORRECTA!, la suma es =   54
Has tenido 1 sumas buenas 
La suma propuesta es 83 + 72 = 
Digita el valor de la suma =  23
¡INCORRECTO!, vuelve a intentarlo 
La suma propuesta es 70 + 70 = 
Digita el valor de la suma =  140
¡RESPUESTA CORRECTA!, la suma es =   140
Has tenido 2 sumas buenas 
La suma propuesta es 90 + 60 = 
Digita el valor de la suma =  150
¡RESPUESTA CORRECTA!, la suma es =   150
Has tenido 3 sumas buenas 
La suma propuesta es 77 + 49 = 
Digita el valor de la suma =  150
¡INCORRECTO!, vuelve a intentarlo 
La suma propuesta es 68 + 64 = 
Digita el valor de la suma =  132
¡RESPUESTA CORRECTA!, la suma es =   132
Has tenido 4 sumas buenas 
La suma propuesta es 23 + 81 = 
Digita el valor de la suma =  104
¡RESPUESTA CORRECTA!, la suma es =   104
Has tenido 5 sumas buenas 
¡FELICIDADES, TERMINASTE!


In [ ]:
#Ejercicio número 15
import random as rn 
longitud = int(input('diga la longitud de la cadena: '))
def fun():
    contador_intentos=0
    numero1 =''
    if longitud >= 2 and longitud <= 9:
        for i in range(longitud):
            a = rn.randint(0,9)
            num = str(a)
            numero1 = numero1 + num
        usuario = input('intente adivinar la cadena: ')  
        contador_intentos += 1
        len_usuario = len(usuario)
        
        while len_usuario != longitud:
            usuario = input('la longitud de la cadena ingresada es diferente a la inicial. intente adivinar la cadena: ')
            len_usuario = len(usuario)
        aciertos = 0
        while aciertos < longitud: 
            aciertos = 0
            for j in range(longitud):
                if numero1[j] == usuario [j]:
                    aciertos = aciertos + 1
            if aciertos == longitud: 
                print(f'con {usuario} ha adivinado {aciertos} valores.')
                print('numero de intentos: ',contador_intentos)
                break
            else: 
                usuario = input(f'con {usuario} ha adivinado {aciertos} valores. intente adivinar la cadena: ')
                contador_intentos += 1
                len_usuario = len(usuario)
                while len_usuario != longitud: 
                    usuario = input('la longitud de la cadena ingresada es diferente a la inicial. intente adivinar la cadena: ')
                    len_usuario = len(usuario)
        else: 
            print('la longitud de la cadena ingresada no se encuentra dentro del parametro del ejercicio.')
fun()            
                
                                
        
            
        

diga la longitud de la cadena: 4
intente adivinar la cadena: 1234
con 1234 ha adivinado 0 valores. intente adivinar la cadena: 1243
con 1243 ha adivinado 0 valores. intente adivinar la cadena: 1324
con 1324 ha adivinado 1 valores. intente adivinar la cadena: 4321
con 4321 ha adivinado 1 valores. intente adivinar la cadena: 2134
con 2134 ha adivinado 0 valores. intente adivinar la cadena: 3124
